### ISSUE TITLE
Tests don't compile with HAVE_CHECK

### ISSUE THREAD

**Issue by nickaj** [EPCCed/exaflow-exags-upc#7]
We require check to run our tests. To enable check and to have the tests do something, we must pass -DHAVE_CHECK as a compiler flag, but we don't

On Ubuntu, and possibly others, with Clang we must link with -lm -lpthreads -lsubunit -lcheck to get a functional compile.

**Comment by njansson** [comment]
Hmm, shouldn't be necessary,  `make check` should compile and run everything.

For the link flags, that should be picked up by the pkg-config file of libcheck [https://libcheck.github.io/check/](url), if `--enable-check` is give to configure (I think the default is `--disable-check`

**Comment by nickaj** [comment]
Yes, I spotted it now and can confirm it's okay with Clang. I just need to improve the README

**Comment by nickaj** [comment]
Updated README. Closing
